/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC 13
 */
public class ViewIMC extends javax.swing.JFrame {

    /**
     * Creates new form viewIMC
     */
    public ViewIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_altura = new javax.swing.JLabel();
        jl_peso = new javax.swing.JLabel();
        jl_result = new javax.swing.JLabel();
        jtf_altura = new javax.swing.JTextField();
        jtf_peso = new javax.swing.JTextField();
        jb_calcular = new javax.swing.JButton();
        jtf_result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_altura.setText("Altura");
        getContentPane().add(jl_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jl_peso.setText("Peso");
        getContentPane().add(jl_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jl_result.setText("Resultado");
        getContentPane().add(jl_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 20));
        getContentPane().add(jtf_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, -1));
        getContentPane().add(jtf_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        jb_calcular.setBackground(new java.awt.Color(0, 153, 0));
        jb_calcular.setText("Calcular");
        getContentPane().add(jb_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, 40));

        jtf_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_resultActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_calcular;
    private javax.swing.JLabel jl_altura;
    private javax.swing.JLabel jl_peso;
    private javax.swing.JLabel jl_result;
    public javax.swing.JTextField jtf_altura;
    public javax.swing.JTextField jtf_peso;
    public javax.swing.JTextField jtf_result;
    // End of variables declaration//GEN-END:variables
}
